name: "App01-Deployment"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
env:
  TF_VAR_CLIENT: ${{ secrets.ARM_CLIENT_ID }}
  TF_VAR_SUB_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TF_VAR_TENANT: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}


jobs:
  create-resource:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6

      - name: Terraform Init
        run: terraform init
    
      - name: Terraform plan
        id: plan
        run: terraform plan -out="main.tfplan" -var-file="deploy.tfvars" -input=false

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: |
          echo "plan successful"
          exit 1

      - name: App01 Infra Deployment
        run: terraform apply --auto-approve "main.tfplan"
